const ROLES = {
  SUPER_ADMIN: 'super_admin',
  MANAGER: 'manager',
  HR: 'hr',
  EMPLOYEE: 'employee',
  IT: 'it',
  PAYROLL: 'payroll',
};

const ALL_ROLES = Object.values(ROLES);

const PERMISSIONS = {
  // Dashboard
  VIEW_ALL_DASHBOARD: [ROLES.SUPER_ADMIN],
  VIEW_TEAM_DASHBOARD: [ROLES.MANAGER],
  VIEW_HR_DASHBOARD: [ROLES.HR],
  VIEW_SELF_DASHBOARD: [ROLES.EMPLOYEE, ROLES.IT, ROLES.PAYROLL],

  // Employee Management
  CREATE_EMPLOYEE: [ROLES.SUPER_ADMIN, ROLES.HR],
  VIEW_ALL_EMPLOYEES: [ROLES.SUPER_ADMIN, ROLES.HR],
  VIEW_TEAM_EMPLOYEES: [ROLES.MANAGER],
  EDIT_EMPLOYEE: [ROLES.SUPER_ADMIN, ROLES.HR],
  DELETE_EMPLOYEE: [ROLES.SUPER_ADMIN],

  // Attendance
  VIEW_ALL_ATTENDANCE: [ROLES.SUPER_ADMIN],
  VIEW_TEAM_ATTENDANCE: [ROLES.MANAGER, ROLES.HR],
  VIEW_SELF_ATTENDANCE: ALL_ROLES,
  CLOCK_IN_OUT: ALL_ROLES,

  // Leaves
  APPLY_LEAVE: ALL_ROLES,
  APPROVE_LEAVE_TEAM: [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  VIEW_ALL_LEAVES: [ROLES.SUPER_ADMIN, ROLES.HR],
  MANAGE_ALL_LEAVES: [ROLES.SUPER_ADMIN],

  // Holiday Calendar
  MANAGE_HOLIDAYS: [ROLES.SUPER_ADMIN, ROLES.HR],
  VIEW_HOLIDAYS: ALL_ROLES,

  // Org Chart
  VIEW_ORG_CHART: ALL_ROLES,

  // Directory
  VIEW_DIRECTORY: ALL_ROLES,

  // Recruitment
  CREATE_POSITION: [ROLES.SUPER_ADMIN, ROLES.HR],
  VIEW_POSITIONS: ALL_ROLES,
  APPROVE_JD: [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  UPLOAD_RESUME: [ROLES.SUPER_ADMIN, ROLES.HR],
  AI_SHORTLIST: [ROLES.SUPER_ADMIN, ROLES.HR],

  // Interviews
  MANAGE_INTERVIEWS: [ROLES.SUPER_ADMIN, ROLES.MANAGER, ROLES.HR],
  VIEW_INTERVIEWS: [ROLES.SUPER_ADMIN, ROLES.MANAGER, ROLES.HR],

  // Employee Voice
  SUBMIT_VOICE: ALL_ROLES,
  VIEW_VOICE_INBOX: [ROLES.SUPER_ADMIN, ROLES.MANAGER],

  // Payroll
  MANAGE_PAYROLL: [ROLES.SUPER_ADMIN, ROLES.PAYROLL],
  VIEW_OWN_PAYSLIPS: ALL_ROLES,
  VIEW_ALL_PAYSLIPS: [ROLES.SUPER_ADMIN, ROLES.PAYROLL],

  // Resignation
  SUBMIT_RESIGNATION: ALL_ROLES,
  VIEW_RESIGNATION_INBOX: [ROLES.SUPER_ADMIN, ROLES.MANAGER],

  // Policies
  MANAGE_POLICIES: [ROLES.SUPER_ADMIN, ROLES.HR],
  VIEW_POLICIES: ALL_ROLES,

  // Onboarding
  MANAGE_ONBOARDING: [ROLES.SUPER_ADMIN, ROLES.HR],

  // Settings
  VIEW_SETTINGS: ALL_ROLES,
  MANAGE_SYSTEM_SETTINGS: [ROLES.SUPER_ADMIN],

  // Audit Logs
  VIEW_AUDIT_LOGS: [ROLES.SUPER_ADMIN],

  // Notifications
  VIEW_NOTIFICATIONS: ALL_ROLES,

  // Global Search
  GLOBAL_SEARCH: ALL_ROLES,
};

module.exports = { ROLES, ALL_ROLES, PERMISSIONS };
