import type { UserRole } from '@/types/auth.types';
import { ALL_ROLES, ROLES } from './roles';

const { SUPER_ADMIN, MANAGER, HR, EMPLOYEE, IT, PAYROLL } = ROLES;

export const PERMISSIONS = {
  VIEW_ALL_DASHBOARD: [SUPER_ADMIN],
  VIEW_TEAM_DASHBOARD: [MANAGER],
  VIEW_HR_DASHBOARD: [HR],
  VIEW_SELF_DASHBOARD: [EMPLOYEE, IT, PAYROLL],

  CREATE_EMPLOYEE: [SUPER_ADMIN, HR],
  VIEW_ALL_EMPLOYEES: [SUPER_ADMIN, HR],
  VIEW_TEAM_EMPLOYEES: [MANAGER],
  EDIT_EMPLOYEE: [SUPER_ADMIN, HR],
  DELETE_EMPLOYEE: [SUPER_ADMIN],

  VIEW_ALL_ATTENDANCE: [SUPER_ADMIN],
  VIEW_TEAM_ATTENDANCE: [MANAGER, HR],
  VIEW_SELF_ATTENDANCE: ALL_ROLES,
  CLOCK_IN_OUT: ALL_ROLES,

  APPLY_LEAVE: ALL_ROLES,
  APPROVE_LEAVE_TEAM: [SUPER_ADMIN, MANAGER],
  VIEW_ALL_LEAVES: [SUPER_ADMIN, HR],
  MANAGE_ALL_LEAVES: [SUPER_ADMIN],

  MANAGE_HOLIDAYS: [SUPER_ADMIN, HR],
  VIEW_HOLIDAYS: ALL_ROLES,

  VIEW_ORG_CHART: ALL_ROLES,
  VIEW_DIRECTORY: ALL_ROLES,

  CREATE_POSITION: [SUPER_ADMIN, HR],
  VIEW_POSITIONS: ALL_ROLES,
  APPROVE_JD: [SUPER_ADMIN, MANAGER],
  UPLOAD_RESUME: [SUPER_ADMIN, HR],
  AI_SHORTLIST: [SUPER_ADMIN, HR],
  MANAGE_INTERVIEWS: [SUPER_ADMIN, MANAGER, HR],
  VIEW_INTERVIEWS: [SUPER_ADMIN, MANAGER, HR],

  SUBMIT_VOICE: ALL_ROLES,
  VIEW_VOICE_INBOX: [SUPER_ADMIN, MANAGER],

  MANAGE_PAYROLL: [SUPER_ADMIN, PAYROLL],
  VIEW_OWN_PAYSLIPS: ALL_ROLES,
  VIEW_ALL_PAYSLIPS: [SUPER_ADMIN, PAYROLL],

  SUBMIT_RESIGNATION: ALL_ROLES,
  VIEW_RESIGNATION_INBOX: [SUPER_ADMIN, MANAGER],

  MANAGE_POLICIES: [SUPER_ADMIN, HR],
  VIEW_POLICIES: ALL_ROLES,

  MANAGE_ONBOARDING: [SUPER_ADMIN, HR],

  VIEW_SETTINGS: ALL_ROLES,
  MANAGE_SYSTEM_SETTINGS: [SUPER_ADMIN],

  VIEW_AUDIT_LOGS: [SUPER_ADMIN],
  VIEW_NOTIFICATIONS: ALL_ROLES,
  GLOBAL_SEARCH: ALL_ROLES,
} as const satisfies Record<string, readonly UserRole[]>;

export type Permission = keyof typeof PERMISSIONS;

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return (PERMISSIONS[permission] as readonly string[]).includes(role);
}
