const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const EmployeeForm = sequelize.define('EmployeeForm', {
  id:            { type: DataTypes.INTEGER.UNSIGNED, autoIncrement: true, primaryKey: true },
  user_id:       { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, unique: true },
  // Joining Letter
  letter_date:         { type: DataTypes.DATEONLY, allowNull: true },
  joining_date:        { type: DataTypes.DATEONLY, allowNull: true },
  joining_designation: { type: DataTypes.STRING(200), allowNull: true },
  joining_address:     { type: DataTypes.TEXT, allowNull: true },
  signature_name:      { type: DataTypes.STRING(200), allowNull: true },
  // Personal Info
  middle_name:         { type: DataTypes.STRING(100), allowNull: true },
  present_address:     { type: DataTypes.TEXT, allowNull: true },
  present_city:        { type: DataTypes.STRING(100), allowNull: true },
  present_state:       { type: DataTypes.STRING(100), allowNull: true },
  present_pincode:     { type: DataTypes.STRING(10), allowNull: true },
  present_phone:       { type: DataTypes.STRING(20), allowNull: true },
  permanent_address:   { type: DataTypes.TEXT, allowNull: true },
  permanent_city:      { type: DataTypes.STRING(100), allowNull: true },
  permanent_state:     { type: DataTypes.STRING(100), allowNull: true },
  permanent_pincode:   { type: DataTypes.STRING(10), allowNull: true },
  permanent_phone:     { type: DataTypes.STRING(20), allowNull: true },
  designation:         { type: DataTypes.STRING(200), allowNull: true },
  blood_group:         { type: DataTypes.STRING(5), allowNull: true },
  marital_status:      { type: DataTypes.ENUM('single','married','divorced','widowed'), allowNull: true },
  dob:                 { type: DataTypes.DATEONLY, allowNull: true },
  pan_number:          { type: DataTypes.STRING(20), allowNull: true },
  place_of_birth:      { type: DataTypes.STRING(100), allowNull: true },
  district:            { type: DataTypes.STRING(100), allowNull: true },
  aadhaar_number:      { type: DataTypes.STRING(20), allowNull: true },
  passport_number:     { type: DataTypes.STRING(30), allowNull: true },
  passport_expiry:     { type: DataTypes.DATEONLY, allowNull: true },
  passport_place:      { type: DataTypes.STRING(100), allowNull: true },
  emergency_contact_1: { type: DataTypes.STRING(300), allowNull: true },
  emergency_contact_2: { type: DataTypes.STRING(300), allowNull: true },
  qualification_details: { type: DataTypes.TEXT('long'), allowNull: true,
    get() { const v = this.getDataValue('qualification_details'); return v ? JSON.parse(v) : []; },
    set(v) { this.setDataValue('qualification_details', JSON.stringify(v || [])); } },
  employment_history:  { type: DataTypes.TEXT('long'), allowNull: true,
    get() { const v = this.getDataValue('employment_history'); return v ? JSON.parse(v) : []; },
    set(v) { this.setDataValue('employment_history', JSON.stringify(v || [])); } },
  training_details:    { type: DataTypes.TEXT('long'), allowNull: true,
    get() { const v = this.getDataValue('training_details'); return v ? JSON.parse(v) : []; },
    set(v) { this.setDataValue('training_details', JSON.stringify(v || [])); } },
  family_details:      { type: DataTypes.TEXT('long'), allowNull: true,
    get() { const v = this.getDataValue('family_details'); return v ? JSON.parse(v) : []; },
    set(v) { this.setDataValue('family_details', JSON.stringify(v || [])); } },
  professional_associations: { type: DataTypes.TEXT, allowNull: true },
  hobbies:             { type: DataTypes.TEXT, allowNull: true },
  serious_illness:     { type: DataTypes.TEXT, allowNull: true },
  other_info:          { type: DataTypes.TEXT, allowNull: true },
  status:              { type: DataTypes.ENUM('draft','submitted','approved','rejected'), defaultValue: 'draft' },
  hr_comment:          { type: DataTypes.TEXT, allowNull: true },
  reviewed_by:         { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  reviewed_at:         { type: DataTypes.DATE, allowNull: true },
  submitted_at:        { type: DataTypes.DATE, allowNull: true },
}, { tableName: 'employee_forms', timestamps: true, underscored: true });

module.exports = EmployeeForm;
