import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { recruitmentApi } from '../../api/recruitment.api';
import { queryClient } from '../../config/queryClient';
import Button from '../../components/ui/Button';
import toast from 'react-hot-toast';

export default function CreatePositionPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    title: '', department: '', experience_years: '',
    salary_lpa: '', deadline: '',
    required_skills: '', key_responsibilities: '',
  });
  const [errors, setErrors] = useState({});

  function validate() {
    const e = {};
    if (!form.title.trim()) e.title = 'Job title is required';
    if (!form.department.trim()) e.department = 'Department is required';
    if (!form.required_skills.trim()) e.required_skills = 'Required skills are needed for AI to generate an accurate JD';
    if (!form.key_responsibilities.trim()) e.key_responsibilities = 'Key responsibilities are needed for AI JD generation';
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  const mutation = useMutation({
    mutationFn: (data) => recruitmentApi.createPosition(data),
    onSuccess: (res) => {
      toast.success('JD generated by AI! Review and send to managers.');
      queryClient.invalidateQueries({ queryKey: ['positions'] });
      // Navigate to HR's My JDs page so they can review and send
      navigate('/recruitment/my-jds');
    },
    onError: (err) => toast.error(err.response?.data?.message || 'Failed to create position'),
  });

  function handleSubmit(e) {
    e.preventDefault();
    if (!validate()) return;
    mutation.mutate(form);
  }

  const field = (name, label, opts = {}) => (
    <div className="flex flex-col gap-1">
      <label className="text-sm font-medium text-gray-700">
        {label} {opts.required && <span className="text-red-500">*</span>}
      </label>
      <input
        type={opts.type || 'text'}
        value={form[name]}
        onChange={e => setForm(p => ({ ...p, [name]: e.target.value }))}
        placeholder={opts.placeholder}
        className={`border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 ${errors[name] ? 'border-red-400' : 'border-gray-300'}`}
      />
      {errors[name] && <p className="text-xs text-red-600">{errors[name]}</p>}
    </div>
  );

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-gray-900">Create Job Position</h1>
        <p className="text-gray-400 text-sm mt-1">AI will generate a professional JD — you can review, edit, then send to managers</p>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <form onSubmit={handleSubmit} className="space-y-4" noValidate>

          <div className="grid grid-cols-2 gap-4">
            {field('title',      'Job Title',    { required: true, placeholder: 'e.g. Senior Flutter Developer' })}
            {field('department', 'Department',   { required: true, placeholder: 'e.g. Engineering' })}
          </div>

          <div className="grid grid-cols-2 gap-4">
            {field('experience_years', 'Experience (years)', { placeholder: 'e.g. 3-5' })}
            {field('salary_lpa',       'Salary Offering (LPA)', { placeholder: 'e.g. 8-12 LPA' })}
          </div>

          {field('deadline', 'Application Deadline', { type: 'date' })}

          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-gray-700">Required Skills <span className="text-red-500">*</span></label>
            <textarea
              rows={2}
              value={form.required_skills}
              onChange={e => setForm(p => ({ ...p, required_skills: e.target.value }))}
              placeholder="React, Node.js, MySQL, REST APIs..."
              className={`border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none ${errors.required_skills ? 'border-red-400' : 'border-gray-300'}`}
            />
            {errors.required_skills && <p className="text-xs text-red-600">{errors.required_skills}</p>}
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-gray-700">Key Responsibilities <span className="text-red-500">*</span></label>
            <textarea
              rows={5}
              value={form.key_responsibilities}
              onChange={e => setForm(p => ({ ...p, key_responsibilities: e.target.value }))}
              placeholder="Describe the main responsibilities of this role in detail..."
              className={`border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none ${errors.key_responsibilities ? 'border-red-400' : 'border-gray-300'}`}
            />
            {errors.key_responsibilities && <p className="text-xs text-red-600">{errors.key_responsibilities}</p>}
          </div>

          {/* AI info */}
          <div className="bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-xl p-4 flex items-start gap-3">
            <span className="text-2xl">🤖</span>
            <div>
              <p className="text-sm font-semibold text-blue-800">AI will generate the full JD</p>
              <p className="text-xs text-blue-600 mt-0.5">
                A complete Job Description will be created from your inputs. After generation, you can review it, make edits, and then select which managers to send it to for approval.
              </p>
            </div>
          </div>

          <div className="flex gap-3 pt-2">
            <Button type="button" variant="secondary" onClick={() => navigate('/recruitment/positions')}>Cancel</Button>
            <Button type="submit" loading={mutation.isPending}>
              {mutation.isPending ? '🤖 Generating JD with AI...' : 'Generate JD with AI →'}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
